### ISSUE TITLE
Control Routing Issue

### ISSUE THREAD

**Issue by yaqiz01** [yaqiz01/pir#18]
In case of
```
MetaPipe M {
   Pipe P {
   }
}
```
There's situation where
```
P.tokenBuffer.init = M.tokenDown.out
```
However M is physically located in CU containing P, so this would make `M.tokenDown.out`, which is a tokenOut of the CU becomes a tokenIn of the same CU. 
This appears in generated dot product from spatial due to single stage meta pipeline.
This is a problem with outer loop containing a single inner loop because we were assuming the tokenDown would come from a different CU than the first children stage
I can't think of any work around at the moment other than fusing the loop, or route the local connection through network
@raghup17

**Comment by raghup17** [comment]
Ah yes, this is annoying.
1. Routing the local connection through network seems simplest to begin with, if the routing algorithm can handle such cases. It's not ideal, but we can roll with this initially.
2. As you mentioned, fusion would be nicer.
3. We can add some architecture support within the control block to pick tokenOuts as tokenIns directly. This wouldn't be very expensive (maximum cost: numTokens \* 2:1 MUXes ), but seems wasteful. I haven't given it too much thought.
