### ISSUE TITLE
PIR Example

### ISSUE THREAD

**Issue by yaqiz01** [yaqiz01/pir#2]
PIR pseudo example 

```
Write addr for SramA = (ia * C+ja), for SramB = (ib * D+jb), for SramC = kc
Local calculation: 
val a = SramA(i)
val b = SramB(i*D+j)
val c = SramC(k)
val out1 = a + b
val out2 = b + c
val out3 = out1 + out2
```

Which of following schedule is correct?
Allocation of stages:

```
s0 = Empty Stage
  // Forward ia, ja for WtAddr calc of sramA
  reg(ia, s0) <- ia // Connecting counter ia to input of pipeline register ia at stage s0
  reg(ja, s0) <- ja
s1 = WAStage(sramA):
  ALU: reg(t1,s1) <- reg(ia,s0) * C
  reg(ja,s1) <- reg(ja,s0)
s2 = WAStage(sramA):
  ALU: SramA.wtAddr <- reg(t1,s1) + reg(ja,s1)
  // Forward ib, jb for WtAddr calc of sramB
  ib <- reg(ib, s2)
  jb <- reg(jb, s2)
s3 = WAStage(sramB):
  reg(r2,s3) <- ALU:reg(ib, s2) * D
  reg(jb, s3) <- reg(jb, s2) 
s4 = WAStage(sramB):
  ALU: SramB.wtAddr <- reg(jb, s3) + reg(t2,s3)
  SramC.wtAddr <- kc
 // Forward ib, jb for Rdaddr calc
  reg(i, s4) <- i
  reg(j, s4) <- j
  SramA.rdAddr <- i
  SramC.rdAddr <- k
s5 = RAStage
  ALU reg(t3, s5) <- reg(i, s4) * D 
  reg(a, s5) <- SramA.load
  reg(c, s5) <- SramC.load
s6 = RAStage
  ALU: SramB.rdAddr <- reg(t3, s5) + reg(j, s5)
  reg(a,s6) <- reg(a,s5)
  reg(c,s6) <- reg(c,s5)
s7 = Stage
  ALU: reg(out1,s7) <- reg(a,s6) + SramB.load
  reg(b,s7) <- Sram.load
  reg(c,s7) <- reg(c,s6)
s8 = Stage
 ALU: reg(out2,s8) <- reg(c,s7) + reg(b,s7)
 reg(out1, s7) <- reg(out1, s8)
s9 = Stage
 ALU: reg(out, s9) <- reg(out1,s8) + reg(out2, s8)
```

Allocation of stages:

```
s0 = Empty Stage
s1 = WAStage(sramA):
  ALU: reg(t1,s1) <- ia * C
  reg(ja, s1) <- ja
s2 = WAStage(sramA):
  ALU: SramA.wtAddr <- reg(t1,s1) + reg(ja,s1)
s3 = WAStage(sramB):
  ALU: reg(t2,s3) <- ib * D
  reg(jb, s3) <- jb
s4 = WAStage(sramB):
  ALU: SramB.wtAddr<- reg(jb, s3) + reg(t2,s3)
  SramC.wtAddr <- kc
 // Forward ib, jb for Rdaddr calc
  reg(i, s4) <- i
  reg(j, s4) <- j
  SramA.rdAddr <- i
  SramC.rdAddr <- k
s5 = RAStage
  ALU: reg(t3, s5) <- reg(i, s4) * D
  reg(j, s5) <- reg(j, s4)
  reg(a, s5) <- SramA.load
  reg(c, s5) <- SramC.load
s6 = RAStage
  ALU: SramB.rdAddr <- reg(t3, s5) + reg(j, s5)
  reg(a,s6) <- reg(a,s5)
  reg(c,s6) <- reg(c,s5)
s7 = Stage
  ALU: reg(out1,s7) <- reg(a,s6) + SramB.load
  reg(b,s7) <- Sram.load
  reg(c,s7) <- reg(c,s6)
s8 = Stage
 ALU: reg(out2,s8) <- reg(c,s7) + reg(b,s7)
 reg(out1, s8) <- reg(out1, s7)
s9 = Stage
 ALU: reg(out, s9) <- reg(out1,s8) + reg(out2, s8)
```

Seems currently PIR doesn't have enough semantics to express all these information

@raghup17 @dkoeplin

**Comment by dkoeplin** [comment]
@blackwings-01

Quick followup question with this. In the convention with the empty stage as the 0th stage, is 

Stage(..., sram.load, ...) the same as Stage(..., CU.load(s0, sram) ...)

**Comment by yaqiz01** [comment]
Those would be different. sram.load still means loading directly from sram. where CU.load(s0, sram) would load from register in the empty stage s0. However, CU.load(s0, sram) would probably never be used since in case of using counter as read addr directly, it take 1 cycle for the data to come back so data would be forwarded to the first stage rather than 0th stage. So in case of using counter as read addr, if stage 1 uses the loaded value, it should refer to sram.load. If it's any other stage sx using loaded value, it should refer to its previous stage using CU.load(sx-1, sram)

**Comment by yaqiz01** [comment]
I would also remove CU.rdAddr and CU.wtAddr from API since we are assuming read addr and write addr are directly from the ALU without going to the registers.
Stage(sx, operands=List(...), op=X, results=List(SramA.readAddr))
I can't think of a case where we need a special register there at the moment. If there's a case, I can always add it back.

**Comment by dkoeplin** [comment]
So if CU.rdAddr and CU.wtAddr have been removed, does that mean the read/write addresses are no longer included in the SRAM declaration if they are the output of some ALU?

**Comment by yaqiz01** [comment]
Yes. The dot product and GDA example should be up to date now.
In case when SRAM's read addr is from counter directly, it is still passed in at SRAM, an example would be

```
      val sigmaBlk = SRAM(size=256, vec=sigmaBlkVec, readAddr=acc(0) , writeAddr=rr(0))
```

which is equivalent to

```
      val sigmaBlk = SRAM(size=256, vec=sigmaBlkVec).rdAddr(acc(0)).wtAdd(rr(0))
```

When read/write addr is from ALU

```
      val xTile   = SRAM(size=4*16, name="xTile", vec=tlXVec)
...
      Stage (s1, op1=t2, op2=CU.ctr(s0, cc(0)), op=FixAdd, result=xTile.readAddr)
```
