### ISSUE TITLE
Pisa Apps

### ISSUE THREAD

**Issue by yaqiz01** [yaqiz01/pir#21]
Ready for testing: 
Without Offchip Access
  `ArgInOutDesign` 
  `DotProductLite`
  `StreamPipe`
  `InOutArgDesign`
  `NiterDesign`
  `SimpleReduceDesign`
  `SimpleSequentialDesign`

Work In Progress:
With OffChip Access
  // With offchip access
  `DotProduct`
  `BlockReduce1DDesign`
  `DeviceMemcpyDesign`
  `DotProductDesign`
  `Memcpy2DDesign`
  `SimpleFoldDesign`
  // Sometimes fail
  `SimpleTileLoadStoreDesign`

-----------------
- [ ] Change all scalar to go through FIFO. 
- [ ] Memory controller load config fixing.

**Comment by raghup17** [comment]
`ArgInOutDesign:`   @blackwings-01 
- [x] One of the control switch output is configured to be 'ne_3', meaning "3rd input link in NE direction". However, control switches have only one link in each of NW, NE, SE, and SW directions. 
- [x] incXbar configuration has the number '31'. Given that we only have 8 token ins in each CU, this isn't valid.
- [x] tokenOutXbar: Too many entries in outSelect. Number of entries should match the number of tokenOuts (8)
- [x] outSelect for control switch (0,0): Too many entries in outSelect. Number of entries should be 33 (8W + 8N + 1 NE + 8E + 8S outputs).
